// <auto-generated />
using System;
using ExpenseManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ExpenseManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseManagement.Models.Budget", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AllocatedById").HasColumnType("int");
                b.Property<DateTime>("AllocatedOn").HasColumnType("datetime2");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Purpose").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("OverspentAmount").HasColumnType("decimal(18,2)");
                b.Property<decimal>("ReturnedBalance").HasColumnType("decimal(18,2)");
                b.Property<decimal>("SpentAmount").HasColumnType("decimal(18,2)");
                b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,2)");
                b.Property<DateTime?>("ValidUntil").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("AllocatedById");
                b.HasIndex("EmployeeId");
                b.ToTable("Budgets");
            });

            modelBuilder.Entity("ExpenseManagement.Models.ExpenseClaim", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AccountTeamRemarks").HasColumnType("nvarchar(max)");
                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<int>("BudgetId").HasColumnType("int");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<DateTime>("ExpenseDate").HasColumnType("datetime2");
                b.Property<int?>("ExpenseReportId").HasColumnType("int");
                b.Property<string>("ReceiptFileName").HasColumnType("nvarchar(max)");
                b.Property<string>("ReceiptPath").HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("ReviewedOn").HasColumnType("datetime2");
                b.Property<int?>("ReviewedById").HasColumnType("int");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTime>("SubmittedOn").HasColumnType("datetime2");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.HasIndex("BudgetId");
                b.HasIndex("EmployeeId");
                b.HasIndex("ExpenseReportId");
                b.HasIndex("ReviewedById");
                b.ToTable("ExpenseClaims");
            });

            modelBuilder.Entity("ExpenseManagement.Models.ExpenseReport", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AccountTeamNotes").HasColumnType("nvarchar(max)");
                b.Property<int?>("AccountTeamVerifiedById").HasColumnType("int");
                b.Property<DateTime?>("AccountTeamVerifiedOn").HasColumnType("datetime2");
                b.Property<bool>("BalanceTransferred").HasColumnType("bit");
                b.Property<DateTime?>("BalanceTransferredOn").HasColumnType("datetime2");
                b.Property<int>("BudgetId").HasColumnType("int");
                b.Property<DateTime>("CreatedOn").HasColumnType("datetime2");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<DateTime?>("ForwardedToAccountTeamOn").HasColumnType("datetime2");
                b.Property<string>("ManagementFeedback").HasColumnType("nvarchar(max)");
                b.Property<string>("ManagementNotes").HasColumnType("nvarchar(max)");
                b.Property<int?>("ManagementReviewedById").HasColumnType("int");
                b.Property<DateTime?>("ManagementReviewedOn").HasColumnType("datetime2");
                b.Property<string>("ReportTitle").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("RemainingBalanceAtSubmission").HasColumnType("decimal(18,2)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("Summary").HasColumnType("nvarchar(max)");
                b.Property<int?>("TransferredToBudgetId").HasColumnType("int");
                b.Property<decimal>("TotalApproved").HasColumnType("decimal(18,2)");
                b.Property<decimal>("TotalClaimed").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("AccountTeamVerifiedById");
                b.HasIndex("BudgetId");
                b.HasIndex("EmployeeId");
                b.HasIndex("ManagementReviewedById");
                b.HasIndex("TransferredToBudgetId");
                b.ToTable("ExpenseReports");
            });

            modelBuilder.Entity("ExpenseManagement.Models.Notification", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Icon").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("IsRead").HasColumnType("bit");
                b.Property<string>("Link").HasColumnType("nvarchar(max)");
                b.Property<string>("Message").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Notifications");
            });

            modelBuilder.Entity("ExpenseManagement.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Department").HasColumnType("nvarchar(max)");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("Role").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Users");
            });

            modelBuilder.Entity("ExpenseManagement.Models.Budget", b =>
            {
                b.HasOne("ExpenseManagement.Models.User", "AllocatedBy").WithMany().HasForeignKey("AllocatedById").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ExpenseManagement.Models.User", "Employee").WithMany("Budgets").HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("AllocatedBy");
                b.Navigation("Employee");
            });

            modelBuilder.Entity("ExpenseManagement.Models.ExpenseClaim", b =>
            {
                b.HasOne("ExpenseManagement.Models.Budget", "Budget").WithMany("ExpenseClaims").HasForeignKey("BudgetId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ExpenseManagement.Models.User", "Employee").WithMany("ExpenseClaims").HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ExpenseManagement.Models.ExpenseReport", "ExpenseReport").WithMany("ExpenseClaims").HasForeignKey("ExpenseReportId");
                b.HasOne("ExpenseManagement.Models.User", "ReviewedBy").WithMany().HasForeignKey("ReviewedById").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Budget");
                b.Navigation("Employee");
                b.Navigation("ExpenseReport");
                b.Navigation("ReviewedBy");
            });

            modelBuilder.Entity("ExpenseManagement.Models.ExpenseReport", b =>
            {
                b.HasOne("ExpenseManagement.Models.User", "AccountTeamVerifiedBy").WithMany().HasForeignKey("AccountTeamVerifiedById").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("ExpenseManagement.Models.Budget", "Budget").WithMany("ExpenseReports").HasForeignKey("BudgetId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ExpenseManagement.Models.User", "Employee").WithMany("ExpenseReports").HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ExpenseManagement.Models.User", "ManagementReviewedBy").WithMany().HasForeignKey("ManagementReviewedById").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("AccountTeamVerifiedBy");
                b.Navigation("Budget");
                b.Navigation("Employee");
                b.Navigation("ManagementReviewedBy");
            });

            modelBuilder.Entity("ExpenseManagement.Models.Notification", b =>
            {
                b.HasOne("ExpenseManagement.Models.User", "User").WithMany("Notifications").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("ExpenseManagement.Models.User", b =>
            {
                b.Navigation("Budgets");
                b.Navigation("ExpenseClaims");
                b.Navigation("ExpenseReports");
                b.Navigation("Notifications");
            });

            modelBuilder.Entity("ExpenseManagement.Models.Budget", b =>
            {
                b.Navigation("ExpenseClaims");
                b.Navigation("ExpenseReports");
            });

            modelBuilder.Entity("ExpenseManagement.Models.ExpenseReport", b =>
            {
                b.Navigation("ExpenseClaims");
            });
#pragma warning restore 612, 618
        }
    }
}
